import CampaignModal from '@/components/CampaignModal'
import GenericTable from '@/components/GenericTable'
import Nav from '@/components/Nav'
import { getCampaigns } from '@/firebase'
import Head from 'next/head'
import React, { useEffect, useState } from 'react'

export default function campaigns() {
    const [campaignModalVisible, setCampaignModalVisible] = useState(false)
    const [campaignList, setCampaignList] = useState([{}])
    const [selectedCampaign, setSelectedCampaign] = useState(null)

    useEffect(() => {
        getCampaigns().then((snap) => {
            const res = snap.val()
            if (res) {
                setCampaignList(() => Object.values(res))
            }
        })
        if (!campaignModalVisible) {
            setSelectedCampaign(null)
        }
    }, [campaignModalVisible])

    useEffect(() => {
        if (selectedCampaign) {
            setCampaignModalVisible(true)
        }
    }, [selectedCampaign])
    return (
        <>
            <Head>
                <title>Dotseemple Admin</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className='w-full h-screen bg-black text-white'>
                <Nav />
                <div className='p-3 h-screen w-full lg:w-11/12 m-auto' >
                    <h1>Campaign Creator</h1>
                    <div className='w-full flex flex-row items-center justify-between space-x-3'>
                        <p className='py-3 text-xs md:text-base'>Create your drop featured link campaigns here</p>
                        <button onClick={() => setCampaignModalVisible(() => !campaignModalVisible)} className="btn btn-sm md:btn-md btn-outline">Create campagin</button>
                    </div>
                    <GenericTable onSelect={(value) => setSelectedCampaign(value)} tableData={campaignList} ignoreCols={['success_message', 'confirm_message', 'id', 'title', 'participants']} />
                </div>
                <CampaignModal editData={selectedCampaign} setVisible={(val) => setCampaignModalVisible(val)} visible={campaignModalVisible} />
            </main>
        </>
    )
}
