import DropTable from '@/components/DropTable'
import Nav from '@/components/Nav'
import { getDrops } from '@/firebase'
import Head from 'next/head'
import React, { useEffect, useState } from 'react'

export default function drop() {

    const [drops, setDrops] = useState({})
    const [title, setTitle] = useState('')

    useEffect(() => {
        getDrops().then((snap) => {
            const res = snap.val()
            if (res) {
                setTitle(Object.values(res).at(-1).title)
                setDrops(Object.values(res).at(-1).participants || [])
            }
        })
    })

    return (
        <>
            <Head>
                <title>Dotseemple Admin</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className='w-full h-screen bg-black text-white'>
                <Nav />
                <div className='p-3 h-screen w-full lg:w-11/12 m-auto' >
                    <h1>Current Drop: <span className='font-bold text-xl tracking-widest text-white'>{title}</span></h1>
                    <p className='py-3'>View handle and wallet address of users participated in the current drop.</p>
                    <DropTable tableData={drops} />
                </div>
            </main>
        </>
    )
}
