import LinkTable from '@/components/LinkTable'
import Nav from '@/components/Nav'
import Head from 'next/head'
import React, { useEffect, useState } from 'react'
import { auth, db } from '@/firebase'
import { ref, onValue } from "firebase/database";
import { useAuthState } from 'react-firebase-hooks/auth'
import { useRouter } from 'next/router';
import { creds } from '@/mixins';

export default function mailbox() {
    const [list, setList] = useState([{}])
    const [total, setTotal] = useState(0)
    const [user] = useAuthState(auth)
    const router = useRouter()
    useEffect(() => {
        onValue(ref(db), (snapshot) => {
            setList([]);
            const res = snapshot.val();
            try {
                res.data !== undefined ? Object.values(res.data).map((entry) => {
                    const cleanEntry = { handle: entry.handle, wallet: entry.wallet, ...entry.linkEntry }
                    entry.linkEntry && setList((oldArray) => [...oldArray, cleanEntry]);
                }) : setList([])
            } catch (_) {

            }
        });
    }, []);

    const checkIfValidAdmin = (user) => {
        if (user.email !== creds.superuser) {
            router.push('/login')
        }
    }

    useEffect(() => {
        if (user !== null) { checkIfValidAdmin(user) } else {
            router.push('/login')
        }
    }, [user])
    
    return (
        <>
            <Head>
                <title>Dotseemple Admin</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className='w-full h-screen bg-black text-white'>
                <Nav />
                <div className='p-3 h-screen w-full lg:w-11/12 m-auto' >
                    <h1>Mailbox</h1>
                    <h3>Total of {total} entries</h3>
                    <p className='py-3'>View submitted tweet link entries of users that can be approved for points</p>
                    <LinkTable setTotal={(val) => setTotal(val)} listData={list} />
                </div>
            </main>
        </>
    )
}
