import CodeCard from '@/components/CodeCard'
import Head from 'next/head'
import Nav from '@/components/Nav';
import { React, useState, useEffect } from 'react'
import { auth, db } from '@/firebase'
import { set, ref, onValue, remove, update } from "firebase/database";
import { useAuthState } from 'react-firebase-hooks/auth'
import { useRouter } from 'next/router';

import swal from 'sweetalert';

export default function DotSeempleCodes() {
    const [quote, setQuote] = useState('')
    const [user] = useAuthState(auth)
    const router = useRouter()

    useEffect(() => {
        onValue(ref(db, 'QOTD'), (snapshot) => {
            const res = snapshot.val()
            if (res !== null) {
                setQuote(res)
            }
        });
    }, []);

    const checkIfValidAdmin = (user) => {
        if (user.email !== 'dotseemple@gmail.com') {
            router.push('/login')
        }
    }

    useEffect(() => {
        if (user !== null) { checkIfValidAdmin(user) } else {
            router.push('/login')
        }
    }, [user])

    const submit = () => {
        update(ref(db), { QOTD: quote})
        setAlert('', 'Successfully published quote!')
    }

    const setAlert = (title, message) => {
        swal({
            title: title,
            text: message,
            timer: 2500,
            showCancelButton: false,
            button: false
        }).then(
            function () { },
            function (dismiss) {
                if (dismiss === 'timer') {
                }
            });
    }

    return (

        <>
            <Head>
                <title>Dotseemple Admin</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className='w-full'>
                <Nav />
                <div className='App w-full h-screen bg-black' >
                    <div className='w-5/6 md:w-1/2 m-auto h-screen flex flex-col space-y-5 items-center justify-center'>
                        <textarea placeholder="Dot's Quotable quote" value={quote} onChange={(e) => setQuote(e.target.value)} className="textarea bg-black text-white resize-none border-white textarea-bordered textarea-lg w-full text-center italic tracking-widest hover:outline-none focus:outline-none" ></textarea>
                        <button onClick={submit} className="btn btn-outline outline-white text-white">Publish!</button>
                    </div>
                </div>
            </main>
        </>
    )
}
